{
 "title": "food assistant",
 "time": { "from": "now-1M/M", "to": "now-1M/M" },
 "refresh": "30s",
 "panels": [
  { "title": "Average stats of RAG APP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Feedback Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(feedback) AS avg_feedback_score\nFROM feedback;\n"
    }
   ]
  },
  {
   "title": "Feedback Rate (Percentage of Conversations with Feedback)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (COUNT(feedback.id)::FLOAT / COUNT(conversations.id)) * 100 AS feedback_rate\nFROM conversations\nLEFT JOIN feedback ON conversations.id = feedback.conversation_id;"
    }
   ]
  },
  {
   "title": "Average Total Token per prompt",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(total_tokens) FROM conversations "
    }
   ]
  },
  {
   "title": "Percentage of High Relevance Responses:",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (COUNT(*) FILTER (WHERE relevance = 'RELEVANT')::FLOAT / COUNT(*)) * 100 AS high_relevance_percentage\nFROM conversations;\n"
    }
   ]
  },
  {
   "title": "Average Prompt Tokens vs Completion Tokens",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(prompt_tokens) AS avg_prompt_tokens, AVG(completion_tokens) AS avg_completion_tokens\nFROM conversations;"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select AVG(response_time) FROM conversations "
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Last 5 conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  question,\r\n  answer,\r\n  relevance\r\nFROM conversations\r\nORDER BY timestamp DESC\r\nLIMIT 5\r\n-- select timestamp as time, question, answer, relevance from conversations \r\n-- WHERE time BETWEEN  $__timeFrom() AND $__timeTo() "
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  total_tokens\r\nFROM conversations\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "+1/-1",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(CASE WHEN feedback > 0 THEN 1 ELSE 0 END) as thumbs_up,\r\n  SUM(CASE WHEN feedback < 0 THEN 1 ELSE 0 END) as thumbs_down\r\nFROM feedback\r\n-- WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\n"
    }
   ]
  },
  {
   "title": "Relevancy",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  relevance,\r\n  COUNT(*) as count\r\nFROM conversations\r\n-- WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY relevance"
    }
   ]
  },
  {
   "title": "Model used",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  model_used,\r\n  COUNT(*) as count\r\nFROM conversations\r\n-- WHERE timestamp BETWEEN $__timeFrom() AND $__timeTo()\r\nGROUP BY model_used\r\n"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  timestamp AS time,\r\n  response_time\r\nFROM conversations\r\nORDER BY time"
    }
   ]
  }
 ]
}